version: '3'
services:
    nginx:
        image: nginx
        ports :
            - "8443:8443/tcp"
        volumes: 
            - ./nginx/certs:/etc/nginx/certs:ro
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./web:/var/www:ro
    server:
        build:
            context: .
            dockerfile: ./server/Dockerfile
        ports:
            - "4000:4000"
    
